# Generated by Django 3.1 on 2020-09-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factcheck',
            name='id',
        ),
        migrations.AlterField(
            model_name='factcheck',
            name='title',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
